<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Hub.Core\Hub.Core.csproj" />
    <ProjectReference Include="..\Hub.Data\Hub.Data.csproj" />
    <ProjectReference Include="..\Hub.Manga\Hub.Manga.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
